Repository aquality-automation/aquality-selenium-core-dotnet, pull requests merged in 2019-09, with the labels that each got.

#17 Fix elementStateProvider, removed web-specific attribute check from it.
  Aquality.Selenium.Core/src/Aquality.Selenium.Core/Elements/Constants.cs
  Aquality.Selenium.Core/src/Aquality.Selenium.Core/Elements/ElementStateProvider.cs
Labels: bug

#19 Add SetApplication and SetServiceProvider methods
  Aquality.Selenium.Core/src/Aquality.Selenium.Core/Applications/ApplicationManager.cs
Labels: enhancement

#16 Feature/override setting with env vars
  Aquality.Selenium.Core/src/Aquality.Selenium.Core/Configurations/LoggerConfiguration.cs
  Aquality.Selenium.Core/src/Aquality.Selenium.Core/Utilities/EnvironmentConfiguration.cs
  Aquality.Selenium.Core/src/Aquality.Selenium.Core/Utilities/JsonFile.cs
  Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Configurations/EnvConfigurationTests.cs
Labels: bug

#22 Add xml documentation to project. Fixes #21
  Aquality.Selenium.Core/src/Aquality.Selenium.Core/Aquality.Selenium.Core.csproj
  Aquality.Selenium.Core/src/Aquality.Selenium.Core/Aquality.Selenium.Core.xml
  Aquality.Selenium.Core/src/Aquality.Selenium.Core/Waitings/ConditionalWait.cs
Labels: bug

#20 added ISettingsFile
  Aquality.Selenium.Core/src/Aquality.Selenium.Core/Applications/Startup.cs
  Aquality.Selenium.Core/src/Aquality.Selenium.Core/Configurations/LoggerConfiguration.cs
  Aquality.Selenium.Core/src/Aquality.Selenium.Core/Configurations/RetryConfiguration.cs
  Aquality.Selenium.Core/src/Aquality.Selenium.Core/Configurations/TimeoutConfiguration.cs
  Aquality.Selenium.Core/src/Aquality.Selenium.Core/Localization/LocalizationManager.cs
  Aquality.Selenium.Core/src/Aquality.Selenium.Core/Utilities/ISettingsFile.cs
  Aquality.Selenium.Core/src/Aquality.Selenium.Core/Utilities/JsonFileExtensions.cs
  Aquality.Selenium.Core/src/Aquality.Selenium.Core/Utilities/JsonSettingsFile.cs
  Aquality.Selenium.Core/src/Aquality.Selenium.Core/Utilities/SettingsFileExtensions.cs
  Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Applications/ApplicationManagerTests.cs
  Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Applications/StartupTests.cs
  Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Aquality.Selenium.Core.Tests.csproj
  Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Configurations/CustomConfigurationTests.cs
  Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Resources/settings.addedparams.json
  Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Utilities/JsonFileTests.cs
Labels: Feature
